### ISSUE TITLE
Download Blockchain

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/cumulus#107] opened 2017-07-22 21:12 UTC
# Node downloads blockchain in initialization

👉  Using last block hash instead of index.
💡 The last block hash is all that the peer needs to provide; the node uses the last block hash to determine what block the peer wants.

**Comment by jordanschalm** [comment] 2017-07-29 19:34
Dupe of #111

**Closed as completed by jordanschalm** 2017-07-29 19:34 UTC
